apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: main1
  region: us-east-1
  version: "1.17"
iam:
  withOIDC: true
vpc:
  cidr: 10.2.0.0/16
  # nat:
  #   gateway: Disabled

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyPath: virginiav2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      withAddonPolicies:
        imageBuilder: true
        ebs: true
        certManager: true
        externalDNS: true
        albIngress: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
