apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic
  region: us-east-2

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyPath: ohiov2
    iam:
      withAddonPolicies:
        imageBuilder: true
        ebs: true
        certManager: true
        externalDNS: true
        albIngress: true
        cloudWatch: true
  - name: ng-ml
    instanceType: p2.xlarge
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyPath: ohiov2
    iam:
      withAddonPolicies:
        imageBuilder: true
        ebs: true
        certManager: true
        externalDNS: true
        albIngress: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
