apiVersion: v1
kind: Pod
metadata:
  name: amazonlinux
  labels:
    app: amazonlinux
spec:
  containers:
  - image: public.ecr.aws/amazonlinux/amazonlinux:latest
    command: ["sleep", "86400"]
    imagePullPolicy: IfNotPresent
    name: amazonlinux
  restartPolicy: Always
  
