apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: public.ecr.aws/ubuntu/ubuntu:latest
    command: ["sleep", "86400"]
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
